CREATE TABLE song(
    id SERIAL PRIMARY KEY,
    title VARCHAR(50),
    artist CHAR(50)
);

-- 'SERIAL' gives a 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE' "datatype" automatically generated by the DB
-- 'VARCHAR(50)' is a variable-length character datatype w/o any whitespace padding for any extra unused character spaces
-- 'CHAR(50)' is a fixed-length character datatype w/ whitespace padding for any index not filled
/**
     *      song table
     *      |   id  |      title        |        artist         |
     *      -----------------------------------------------------
     *      |1      |'Let it be'        |'Beatles'              |
     *      |2      |'Hotel California' |'Eagles'               |
     *      |3      |'Kashmir'          |'Led Zeppelin'         |
     */

/**
         * Assignment: create a table in problem1.sql called "song" that has 3 columns listed above
         *
         * NOTE: The "id" column is what we are going to define as the primary key.
         */